name: Run Repeato CLI

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  repeato-cli:
    name: Build and run repeato tests using REPEATO CLI
    runs-on: macos-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - uses: actions/checkout@v3

      - name: Checkout flutter app repo
        uses: actions/checkout@v3
        with:
          repository: repeato-qa/flutter-demo-app
          path: demo-app
          clean: false

      - name: Checkout workspace repo
        uses: actions/checkout@v3
        with:
          repository: repeato-qa/demo-workspace
          path: workspace-tests
          clean: false

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@d7b53ddc6e44254e1f4cf4a6ad67345837027a66
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: reactivecircus/android-emulator-runner@d7b53ddc6e44254e1f4cf4a6ad67345837027a66
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: adb install demo-app/app-x86_64-release.apk && npx @repeato/cli-testrunner --workspaceDir "${GITHUB_WORKSPACE}/workspace-tests" --batchId 0 --licenseKey ${{ secrets.REPEATO_LICENSE_KEY }} --outputDir "${GITHUB_WORKSPACE}/batch-report"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: upload-report
          path: batch-report

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: upload-logs
          path: repeato-cli/log.txt
