name: Run Repeato CLI

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  repeato-cli:
    name: Build and run repeato tests using REPEATO CLI
    runs-on: macos-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - uses: actions/checkout@v3

      - name: Checkout flutter app repo
        uses: actions/checkout@v3
        with:
          repository: repeato-qa/flutter-demo-app
          path: demo-app
          clean: false

      - name: Checkout workspace repo
        uses: actions/checkout@v3
        with:
          repository: repeato-qa/demo-workspace
          path: workspace-tests
          clean: false
  
      - name: Start Android emulator and run tests
        uses: ReactiveCircus/android-emulator-runner@v2.26.0
        with:
          api-level: 29
          arch: x86_64
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          target: google_apis
          profile: pixel_3a
          ram-size: 8096M
          script: adb install demo-app/app-x86_64-release.apk && npx @repeato/cli-testrunner --workspaceDir "${GITHUB_WORKSPACE}/workspace-tests" --batchId 0 --licenseKey ${{ secrets.REPEATO_LICENSE_KEY }} --outputDir "${GITHUB_WORKSPACE}/batch-report"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: upload-report
          path: batch-report

      - name: Upload Logs
        uses: actions/upload-artifact@v3
        with:
          name: upload-logs
          path: repeato-cli/log.txt
